# Generated by Django 6.1 on 2026-08-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatus',
            old_name='is_online',
            new_name='online',
        ),
    ]
